# Generated by Django 5.2.4 on 2025-08-08 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTRRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=50)),
                ('employee_name', models.CharField(max_length=100)),
                ('total_hours', models.FloatField(blank=True, null=True)),
                ('nd_reg_hours', models.FloatField(blank=True, null=True)),
                ('absences', models.FloatField(blank=True, null=True)),
                ('tardiness', models.FloatField(blank=True, null=True)),
                ('undertime', models.FloatField(blank=True, null=True)),
                ('ot_regular', models.FloatField(blank=True, null=True)),
                ('nd_ot_reg', models.FloatField(blank=True, null=True)),
                ('ot_restday', models.FloatField(blank=True, null=True)),
                ('nd_restday', models.FloatField(blank=True, null=True)),
                ('ot_rest_excess', models.FloatField(blank=True, null=True)),
                ('nd_rest_excess', models.FloatField(blank=True, null=True)),
                ('ot_special_holiday', models.FloatField(blank=True, null=True)),
                ('nd_special_holiday', models.FloatField(blank=True, null=True)),
                ('ot_sh_excess', models.FloatField(blank=True, null=True)),
                ('nd_sh_excess', models.FloatField(blank=True, null=True)),
                ('ot_legal_holiday', models.FloatField(blank=True, null=True)),
                ('special_holiday', models.FloatField(blank=True, null=True)),
                ('ot_legal_excess', models.FloatField(blank=True, null=True)),
                ('nd_legal_excess', models.FloatField(blank=True, null=True)),
                ('ot_sh_rest', models.FloatField(blank=True, null=True)),
                ('nd_sh_rest', models.FloatField(blank=True, null=True)),
                ('ot_sh_rest_excess', models.FloatField(blank=True, null=True)),
                ('nd_sh_rest_excess', models.FloatField(blank=True, null=True)),
                ('legal_rest', models.FloatField(blank=True, null=True)),
                ('nd_legal_rest', models.FloatField(blank=True, null=True)),
                ('ot_legal_rest_excess', models.FloatField(blank=True, null=True)),
                ('nd_legal_rest_excess', models.FloatField(blank=True, null=True)),
                ('vac_leave_applied', models.FloatField(blank=True, null=True)),
                ('sick_leave_applied', models.FloatField(blank=True, null=True)),
                ('backpay_vl', models.FloatField(blank=True, null=True)),
                ('backpay_sl', models.FloatField(blank=True, null=True)),
                ('ot_regular_excess', models.FloatField(blank=True, null=True)),
                ('nd_ot_reg_excess', models.FloatField(blank=True, null=True)),
                ('legal_holiday', models.FloatField(blank=True, null=True)),
                ('nd_legal_holiday', models.FloatField(blank=True, null=True)),
                ('overnight_rate', models.FloatField(blank=True, null=True)),
                ('project', models.CharField(blank=True, max_length=100, null=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.excelupload')),
            ],
        ),
    ]
