# Generated by Django 5.2.4 on 2025-08-08 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_excelupload_uploaded_by_alter_excelupload_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtrrecord',
            name='sheet_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
