# Generated by Django 5.2.4 on 2025-08-08 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dtrrecord_sheet_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectListRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=100)),
                ('project', models.CharField(max_length=255)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.excelupload')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectManpowerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=100)),
                ('project', models.CharField(max_length=255)),
                ('supervisor', models.CharField(blank=True, max_length=255, null=True)),
                ('tl', models.CharField(blank=True, max_length=255, null=True)),
                ('messenger', models.CharField(blank=True, max_length=255, null=True)),
                ('hk', models.CharField(blank=True, max_length=255, null=True)),
                ('gl', models.CharField(blank=True, max_length=255, null=True, verbose_name='G&L')),
                ('day_off_reliever', models.CharField(blank=True, max_length=255, null=True)),
                ('aa', models.CharField(blank=True, max_length=255, null=True)),
                ('electrician', models.CharField(blank=True, max_length=255, null=True)),
                ('plumber', models.CharField(blank=True, max_length=255, null=True)),
                ('driver', models.CharField(blank=True, max_length=255, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.excelupload')),
            ],
        ),
    ]
