# Generated by Django 5.2.4 on 2025-08-08 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_projectlistrecord_projectmanpowerrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmanpowerrecord',
            old_name='gl',
            new_name='gnl',
        ),
    ]
