# Generated by Django 5.2.4 on 2025-08-08 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_gl_projectmanpowerrecord_gnl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet2Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=255)),
                ('col_a', models.CharField(blank=True, max_length=255, null=True)),
                ('col_b', models.CharField(blank=True, max_length=255, null=True)),
                ('col_c', models.CharField(blank=True, max_length=255, null=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.excelupload')),
            ],
        ),
    ]
