# Generated by Django 5.2.4 on 2025-08-12 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_settings_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='enable_auto_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='layout_spacing',
            field=models.CharField(default='normal', max_length=50),
        ),
        migrations.AddField(
            model_name='settings',
            name='retention_days',
            field=models.IntegerField(default=30),
        ),
    ]
